FROM ubuntu:latest

# set the working directory in image to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install Python and pip
RUN apt-get update && apt-get install -y python3 python3-pip

#set environment variable
ENV NAME World

#run the command to start the application
CMD ["python3", "app.py"] 


# This Dockerfile sets up a simple Python application
# that prints "Hello World!" when run.